apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-configmap
data:
  AUTH_SVC_ADDRESS: "auth:5000"
  MONGODB_VIDEOS_URI: "mongodb://nasi:nasi1234@3.91.20.14:30005/videos?authSource=admin&readPreference=secondary&directConnection=true&ssl=false"
  MONGODB_MP3S_URI: "mongodb://nasi:nasi1234@3.91.20.14:30005/mp3s?authSource=admin&readPreference=secondary&directConnection=true&ssl=false"

