apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "thomasfookins007helby@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "kjkn mhgd gccx eemw"
type: Opaque